services:
  - type: web
    name: purblack-analytics
    env: node
    buildCommand: npm install && NEXT_TELEMETRY_DISABLED=1 npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXT_TELEMETRY_DISABLED
        value: 1
      - key: FULL_ACCESS_PASSWORD
        sync: false
      - key: NEXT_PUBLIC_FULL_ACCESS_PASSWORD
        sync: false
